#! /bin/bash
bspc monitor VGA-1 -d '1' '2' '3' '4' '5' '6' '7' '8' '9' &

export XDG_CURRENT_DESKTOP='bspwm'

sxhkd &
picom &
polybar &
feh --bg-scale ~/Pictures/street.png &
#xrandr --output VGA-1 --primary --mode 1920x1080 --rotate normal --output eDP-1 --off
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 2 &
bspc config window_gap 12 &

bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a Firefox desktop='^1'

bspc config focused_border_color "#a7c080"
bspc config active_border_color "#a7c080"
bspc config normal_border_color "#1e2326"
